name: Push base language translations to Lokalise
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Lokalise
        uses: lokalise/lokalise-push-action@v4.0.0-beta.1
        with:
          api_token: ${{ secrets.LOKALISE_API_TOKEN }}
          project_id: 41063725688788abcfce67.08860322
          base_lang: en
          translations_path: |
            locales
            public/messages
          file_format: json
          file_ext: json
          skip_tagging: true
          additional_params: >
            {
              "tag_inserted_keys": true,
              "tags": ["custom", "another_tag"]
            }